### PR TITLE
A new bumblebee website

### PR DESCRIPTION
**Pull request by rafaelcn**
In this PR it's proposed a new design, flex-box oriented and also the website is generated statically in order to provide quick _changeability_ in the website structure and also easy maintenance. In the future, if new versions of bumblebee are created it would be nice to implement kind of a blog website to manage/present those releases.

A screen shot can be seen below.

image

### CODE REVIEW

**Comment by rafaelcn** [comment]
It would be nice to license the website using CC as well.

**Comment by Lekensteyn** [comment]
Hey Rafael, thanks for this, it looks quite nice.

Quick comment: is it possible to preserve the locations of the old tarballs? Maybe people are interested in older versions for some reason.

**Comment by rafaelcn** [comment]
Of course. Then I gonna improve, adding a page that deals with older tarballs that also links to the releases page of Github.

**Comment by rafaelcn** [comment]
So, as requested, I did preserve the old tarballs. By doing that I designed a new structure for the website which looks cleaner and intuitive.

_Navigation_:

*Home*:
See the news about Bumblebee in a blog way.

*About*:
About the project itself, how to compile it and the wiki.

*Releases*:
Current and older releases of Bumblebee

*Install*:
How to install Bumblebee in different distros.

*Maintainers*:
A page that features every active/non-active maintainer of Bumblebee.

**Comment by rafaelcn** [comment]
Hello, any post review on this PR?

**Comment by Lekensteyn** [comment]
Hi, unfortunately no updates yet, updating the website doesn't seem to be a high priority :/

**Comment by rafaelcn** [comment]
Well, as per the recent progress on the NVidia offloading technology by NVidia itself I will close this PR as the website will be of no use.

**Pull request closed without merging**
